### ISSUE TITLE
object-cache.php does not check that the plugin is enabled / object cache is enabled

### ISSUE THREAD

**Issue by jamieburchell** [BoldGrid/w3-total-cache#1003]
When adding `object-cache.php` to the `wp-content` directory, the object cache is enabled and files are written to disk at `cache/object/key_version_all` even when the W3TC plugin is not installed / the object cache feature is disabled.

In `advanced-cache.php` there are checks such as `if ( $w3tc_config->get_boolean( 'pgcache.enabled' ) )` but there are no such checks in `object-cache.php`.

This is important to me, because my deployment process ensures that the `advanced-cache.php` and `object-cache.php` files are copied to the correct locations (which are not writable by WordPress). In that case, the object cache can become enabled even when I've told it not to be.

Perhaps something like this?

```
	...

	require_once W3TC_DIR . '/w3-total-cache-api.php';

	$w3tc_config = \W3TC\Dispatcher::config();
	if ( ! $w3tc_config->get_boolean( 'objectcache.enabled' ) ) {
		return;
	}

	/**
	 * Init cache
	 *
	 * @return void
	 */
	function wp_cache_init() {
	...
```

**Comment by jamieburchell** [comment]
Thanks @cssjoe !

**Comment by cssjoe** [comment]
@jamieburchell The fallback would just let the dropin act like it wasn't there and leave object caching (non-persistent) to WordPress.

**Comment by jamieburchell** [comment]
> [@jamieburchell](https://github.com/jamieburchell) The fallback would just let the dropin act like it wasn't there and leave object caching (non-persistent) to WordPress.

@cssjoe When the fallback is included, my website grinds to a halt over time and my PHP processes memory grows. When I then enable W3TC object cache, the problem goes away. I'm thinking including the fallback manually as you have here is causing the issue. I think it shouldn't include anything if a persistent backend isn't available. Doesn't WP by default already have a session scoped object cache _without_ needing the object-cache.php drop in?
