### ISSUE TITLE
wp_cache_get always returns false under certain conditions

### ISSUE THREAD

**Issue by dgwatkins** [BoldGrid/w3-total-cache#1012]
Since 2.8.1, when the object cache is set to disk, every cached value we try to get returns false.

Take for example this simple code:
```
wp_cache_set( 'my-key', 'my-value' );
echo wp_cache_get( 'my-key' );  // displays false when called via wp-cli
```

This is causing unexpected issues with WPML.

Is there any specific reason why you are doing this? The commit doesn't give much explanations:
https://github.com/BoldGrid/w3-total-cache/commit/46a46cb3eceef030d771d5cee5e3e32bc5454ea1#diff-1761ac755aed44cd072cde27c3e4d9cf7e0503afcdf9064e0162256b0e7c4df9R188

**Comment by cssjoe** [comment]
@dgwatkins We added that part to skip using Object Cache for WP-CLI calls if it's set to Disk.  It is recommended to use a memory-based type of storage.  Sites with a large number of object cache files stored on disk had issues when running WP-CLI commands.

**Comment by dgwatkins** [comment]
Thanks for your reply.

It means that the following pattern is incorrect:
```
function get_my_key() {
    $value = wp_cache_get( 'my-key' );
    if ( ! $value ) {
        $value = 'my-value';
        wp_cache_set( 'my-key', $value );
    }
    return wp_cache_get( 'my-key' );
}
```
And that we should use this pattern instead:
```
function get_my_key() {
    $value = wp_cache_get( 'my-key' );
    if ( ! $value ) {
        $value = 'my-value';
        wp_cache_set( 'my-key', $value );
    }
    return $value;
}
```
