### ISSUE TITLE
Add an option to disable logs for static files such as JS, CSS, and images for Nginx

### ISSUE THREAD

**Issue by mavas84** [BoldGrid/w3-total-cache#126]
Add an option to disable logs for static files such as JS, CSS, and images. Because keeping logs for static files is constantly increasing the file sizes. 

```
location ~* .(css|gif|ico|jpeg|jpg|js|svg|webp|png)$ {
access_log off;
log_not_found off;
}
```
Reference topic: https://wordpress.org/support/topic/about-nginx/

**Comment by mavas84** [comment]
Another suggestion: https://wordpress.org/support/topic/disable-static-asset-requests-logging/

**Comment by cssjoe** [comment]
Configuring Nginx logging is outside the scope of our plugin.  It would be best for such changes to be made in the server's Nginx configuration.
