### ISSUE TITLE
Ability to Blacklist Query Strings

### ISSUE THREAD

**Issue by lf-jeremy** [BoldGrid/w3-total-cache#137]
It would be helpful to offer the ability to ignore query strings for the purpose of caching a page unless a blacklisted query string (known to not result in deterministic output) is included in the URL.

Most query string parameters in a WordPress site (for the frontend, especially for anonymous users) are not used to dynamically change page output but rather used for JavaScript/analytics/marketing attribution purposes.

For the most part, query strings used by WP Query (e.g. pagination, search, page or post ID, etc) or plugins like Google AMP are the main use case for changing output with query strings in WordPress, but many users have permalinks enabled that use permastructs in place of these query parameters.

For a common (mostly static) marketing website, you may have traffic tagged with query string parameters for utm_source, utm_medium, utm_campaign, etc, and advertising platforms such as Google Ads or Facebook may include parameters of their own that are unique values for every click (gclid, fbclid)...

It is important to be able to cache pages with query strings that don't affect the server's page output dynamically without enabling query string caching that caches each unique query string separately so that way there is a good CACHE HIT rate. With values like gclid or fbclid that are essentially GUIDs, that is very important.

The current implementation option offered by the plugin is to keep "Cache URIs with query string variables" disabled and maintain a whitelist of ignored parameters (either key or key/value) in the "Accepted query strings" field.

That is great until either a bot/crawler hits your site with an unknown query parameter and the cache is bypassed or users, tools, or advertising platforms start adding query string parameters that are not white-listed and you are forced to reactively add to your whitelist.

A blacklist would be a more appropriate option since it would make it more difficult to bypass your cache either unintentionally or maliciously and only behave separately for parameters that are known to change page output. Such a list would require less maintenance and could be proactively updated when such parameters are introduced.

Depending on the needs of the users, these blacklisted query strings could be cached separately by unique key or key/value or not at all, depending on the value of "Cache URIs with query string variables". Going that far may require a way of clarifying if something is blacklisted because it should bypass the cache or because it should be cached separately.

My own use case is simpler and would not involve trying to cache any blacklisted query strings, just using the blacklist to normalize cache keys by deeming a page "the same" and "cacheable" if it either has no query string or has a query string with no blacklisted parameters. That simpler implementation would on its own bring a lot of value.

**Comment by Mte90** [comment]
Any updates for this?
This will be helpful to add parameters used for tracking/ads like `utm` or `gclid`

**Comment by cssjoe** [comment]
We added extra query string arguments to ignore in a previous release.
