### ISSUE TITLE
 Integrate the NEL and Report-to response headers

### ISSUE THREAD

**Issue by mavas84** [BoldGrid/w3-total-cache#156]
Integrate the NEL and Report-to response headers

Reference topic: https://wordpress.org/support/topic/nel-rerpot-to-response-headers/

**Comment by cssjoe** [comment]
In a previous release, we added the "report-to" attribute to the CSP and CSPRO headers on the settings page `wp-admin/admin.php?page=w3tc_browsercache#security`.
