### ISSUE TITLE
Feature Request: prime pgcache via GET

### ISSUE THREAD

**Issue by dingman** [BoldGrid/w3-total-cache#166]
So far, I've only found that you can manually force the pgcache to prime via WPCLI. I would love if there were a way to prime it through a GET instead, or a way to directly hook it into the standard cron which can be run through a GET already. Any ideas or solutions would be greatly appreciated

**Comment by dingman** [comment]
@bwmarkle any feedback or timeline on this?

**Comment by bwmarkle** [comment]
Hi @dingman thanks for following up! I'm not 100% on this, but let me follow up with one of the developers and I'll get back to you on this.

**Comment by dingman** [comment]
Thanks!

The use case is that we run a cluster and do not run cronjobs running on every server, so it would be better to isolate a single server and run a GET on that one server, to prime the cache into Redis.

**Comment by ftownes** [comment]
@bwmarkle i think it makes the most sense if we add functionality that enables WP Cron to be run only when the server's hostname (as a PHP environment variable) is matched or some other environment variable is set, which maps to a single app server.

In this way, the environment can change (e.g. if auto-scaling) or a hostname can be specified if the environment doesn't change frequently. This would be a premium feature.

Thoughts?

**Comment by dingman** [comment]
@ftownes I couldn't find a way, but is there a way to prime cache using the WP Cron as it is today? It seems like that would solve it too and make it less complicated

**Comment by bwmarkle** [comment]
Hi @dingman 

> is there a way to prime cache using the WP Cron as it is today?

Today, there is currently not a way to do this via WP Cron, only WP CLI.

One of our developers did give me some sample code showing how you can create your own script to prime the cache:

```php
$o = \W3TC\Dispatcher::component( 'PgCache_Plugin_Admin' );
$o->prime();
```

I wanted to say hi! and also test out this code, so I created a video to show how it can be used - I hope you have a moment to watch:

https://youtu.be/zymsMcJi6zo
[![Video](https://img.youtube.com/vi/zymsMcJi6zo/0.jpg)](https://www.youtube.com/watch?v=zymsMcJi6zo)

Thanks!
\- Brad

**Comment by bwmarkle** [comment]
Hi @dingman - On a side note, have you explored the **Cache Preload** settings within the _Page Cache_ settings?

**Comment by dingman** [comment]
Hi @bwmarkle yes, that has never seemed to work when WP Cron is disabled.

**Comment by dingman** [comment]
@bwmarkle @ftownes I setup the code above, but it's still not caching all the pages like I had hoped. Can't even tell if it's caching anything beyond the ones I visit.

The goal is that I can get all pages cached and stay cached, across multiple servers, and the cache living in Redis.

TIA!

**Comment by bwmarkle** [comment]
Hi @dingman,

1. It looks like the preloading works off of your sitemap. Are the pages in question in your sitemap?
1. In the video above, I echoed each url to see what was being primed. If you do a similar test adjusting the code here, what do you see? https://github.com/W3EDGE/w3-total-cache/blob/master/PgCache_Plugin_Admin.php#L172

Thanks,
\- Brad

**Comment by dingman** [comment]
@bwmarkle thank you! that did seem to do the trick.

I reverted to a different XML plugin that was more concise with what I want cached and indexed; upon adding the code you wrote, I do see it being cached fully. I also had to increase the number of pages. After looking at the code as you have done.

Seems to be working as expected with that code
