### ISSUE TITLE
Embed pages and manual minify cache

### ISSUE THREAD

**Issue by superpoincare** [BoldGrid/w3-total-cache#21]
Wordpress has the feature to embed pages where it also creates html urls with permalinks like:

https://www.example.com/2019/07/16/example-post/embed/

This has its own css and js provided by Wordpress and is theme independent by default. 

However, if you use W3TC and use minify in the manual mode, the plugin inserts the minified css and js files in the html. This can of course be disabled in the setting "Never minify the following pages:" but since it affects all users, it should be fixed at the plugin level itself. 

Also I see that the HTML minification of embed pages isn't perfect, there are line breaks/whitespace etc.

**Comment by cssjoe** [comment]
This issue appears to be outdated.  Please let us know if there is still an issue.
