### ISSUE TITLE
Implement wp_cache_get_multiple() added in WordPress 5.5.

### ISSUE THREAD

**Issue by mavas84** [BoldGrid/w3-total-cache#239]
wp_cache_get_multiple() is introduced in WP 5.5
Reference topic:
https://wordpress.org/support/topic/implement-wp_cache_get_multiple/

**Comment by spacedmonkey** [comment]
Is there any update on this? There is some serious performance wins that being missed here.

Examples of where this was implemented 

https://github.com/pantheon-systems/wp-redis/commit/d5a57e3a459e0a02aaf3b1d5c735a3bd3f21bda0
https://github.com/Automattic/wp-memcached/pull/88
https://github.com/WordPress/wordpress-develop/commit/ab0feb8b44eca9648f00c74f7932b794307f9ce2

CC @cssjoe @jacobd91 
@cssjoe
jacobd91

**Comment by spacedmonkey** [comment]
Related: #513, #583

**Comment by Mte90** [comment]
Any hope for this?

**Comment by spacedmonkey** [comment]
Here is a write up of that explains the importance of this function. 

https://xwp.co/easy-performance-wins-with-opt-in-caching-improvements/
