### ISSUE TITLE
Azure Storage Library Conflict

### ISSUE THREAD

**Issue by WEWebTeam** [BoldGrid/w3-total-cache#282]
The W3TC plugin includes its own copy of an Azure storage library for supporting the Azure CDN.  It appears that the version being used is not being kept up to date.  As a result, when installing the latest version of the Azure library on our web site for other purposes, it breaks W3TC because some of the functions have been renamed.  Changing lines 150-154 in CdnEngine_Azure.php to the below appears to fix the issue.  If you could update this in the plugin and update your Azure library, that would solve our issue and potentially issues for others.  Not to mention using an older version of the library could have security or other issues.  

Fixed code: 

			$options->setContentMD5( $content_md5 );
			if ( isset( $headers['Content-Type'] ) )
				$options->setContentType( $headers['Content-Type'] );
			if ( isset( $headers['Cache-Control'] ) )
				$options->setCacheControl( $headers['Cache-Control'] );

**Comment by mavas84** [comment]
Hello @WEWebTeam 

Thank you for takind the time to report this.
The devs will make sure to test the behavior and get back to you on this as soon as the tests are performed.
Thanks!

**Comment by cssjoe** [comment]
@WEWebTeam We just updated the Azure library in version 2.7.3.  Please let us know if there is still an issue.  Thank you.
