### ISSUE TITLE
Adjust nested json settings from wp-cli

### ISSUE THREAD

**Issue by jealouscloud** [BoldGrid/w3-total-cache#31]
As it stands, you can enable most caching types from the Cli, in a format similar to:
`wp w3-total-cache option set pgcache.enabled true --type=boolean`

However, as far as I can tell, there is not a way to configure fragment cache options using this method, as fragment cache settings are stored as a JSON object.
```# wp w3-total-cache option get fragmentcache  --type=array
{
    "engine": "file"
}
```

However there is no convenient way to serialize back to the JSON object, the closest serializer is the "array" serializer, which is still incredibly inappropriate:

```# wp w3-total-cache option set fragmentcache '{"engine": "file"}'  --type=array
Success: Option updated successfully 
# wp w3-total-cache option get fragmentcache engine --type=array
[
    "{\"engine\": \"file\"}"
]
```

Ideally the solution would be to allow serialization of nested json data, to some degree. Something such as `--type=object`, or allowing name selection such as `w3-total-cache option set fragmentcache["engine"] file`

Happy to contribute myself if I am correct that this is indeed a needed feature.

**Comment by Respheal** [comment]
Can confirm a need for this! Currently the only way to set nested json variables with the cli is by importing a full config file with `wp w3-total-cache import`.
