### ISSUE TITLE
Stop flushing whole object cache on post update

### ISSUE THREAD

**Issue by mavas84** [BoldGrid/w3-total-cache#344]
The object cache is flushed on EVERY post update. 
Add ability to clear the Object cache only on the specific page once the post is updated.
Reference link: https://wordpress.org/support/topic/stop-flushing-whole-object-cache-on-post-update/

**Comment by archon810** [comment]
Flushing the whole object cache on every little post update makes object cache much less useful as it constantly needs to be recached, potentially with expensive and long queries.

**Comment by maciejmackowiak** [comment]
@mavas84 How about using the purge all objects setting which is already in the plugin:
https://github.com/W3EDGE/w3-total-cache/pull/345

**Comment by archon810** [comment]
Any updates please?

**Comment by archon810** [comment]
Any updates please?

Seems like the fix is ready but it keeps getting punted.
