### ISSUE TITLE
Setup Guide - Why are some options unavailable?

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/w3-total-cache#359]
When I was testing the Database Cache, it says Redis or Memcached are recommended, but those two options were unavailable to me during the test. Can we add language about why? It's confusing when the recommended option isn't available.

![why-unavailable](https://user-images.githubusercontent.com/20601160/113301323-ea7d5c80-92cc-11eb-8e40-76096da719b5.png)

**Comment by cssjoe** [comment]
@nicolepaschen Those storage engines are not detected and appear unavailable in the environment.  I agree that this screen has a need for more information.  The recommendation at the bottom of that slide is a general recommendation.  Users on a shared server may not have those services installed or available to them.

**Comment by avonville** [comment]
@cssjoe 

 I was thinking of adding something like this to the welcome page or it could be on each caching section. What do you think?

![image](https://github.com/user-attachments/assets/f4ba73ea-4f22-4c77-9ad6-3d56be7e4589)

**Comment by avonville** [comment]
Also the recommendation should be before selection and not after imo
