### ISSUE TITLE
Memcached test using SaslAuth

### ISSUE THREAD

**Issue by cssjoe** [BoldGrid/w3-total-cache#448]
From https://wordpress.org/support/topic/memcached-tests-when-use-sasl/

Referenced:
https://github.com/W3EDGE/w3-total-cache/blob/master/Generic_AdminActions_Test.php#L160
https://github.com/W3EDGE/w3-total-cache/blob/master/Util_Installed.php#L128

The credentials are added in the Cache_Memcached class when used, if the passed config includes them:
https://github.com/W3EDGE/w3-total-cache/blob/master/Cache_Memcached.php#L83-L87

The test retrieves the Cache_Memcached instance, which should use the credentials, if passed:
https://github.com/W3EDGE/w3-total-cache/blob/master/Cache.php#L51

The test and check if installed should both pass the username and password from the configuration, if set.

**Comment by macaws** [comment]
I've used two hosting providers that use LSMCD - SASL required. W3TC does not connect to either.

This is the LSMCD spec for handling PHP connections:
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:lsmcd:new_sasl

**Comment by r00t9** [comment]
Any updates to work with SSL ?
