### ISSUE TITLE
W3 Total Cache and ludicrousdb

### ISSUE THREAD

**Issue by archon810** [BoldGrid/w3-total-cache#61]
We've been using ludicrousdb for master/slave db scaling for years, and I've always wondered if it'd be possible to also use W3TC's db caching together with it. 

Both use db.php drop-ins, but according to https://github.com/stuttter/ludicrousdb/issues/83, it's actually possible to make them work together with some tweaks.

It would be killer if this could be achieved.

Thanks.

**Comment by wywarren** [comment]
I'm sort of in the same boat right now. Except it's a cross between ludicrousdb, w3 and query monitor. If I managed to merge the two/three I'll let you know.

**Comment by bwmarkle** [comment]
Hi archon810 and wywarren,

W3 Total Cache Pro includes _dbcluster_. It offers similar functionality to [ludicrousdb](https://github.com/stuttter/ludicrousdb), and is based on the same [HyperDB](https://wordpress.org/plugins/hyperdb/) framework. Our Pro users can skip using using ludicrousdb and instead use our _dbcluster_ framework instead.

**Comment by archon810** [comment]
@bwmarkle I had no idea, because W3TC is terrible at advertising this feature. I don't see `dbcluster` anywhere in the backend UI, upsell, or otherwise (at least in 0.10).

I also don't see it mentioned anywhere meaningful on Google, on W3TC's own page https://www.w3-edge.com/products/w3-total-cache/ (which is pretty barebones), Github other than a few commit mentions https://github.com/W3EDGE/w3-total-cache/search?q=dbcluster&type=Wikis.

I bet this is brand new information to pretty much everyone using W3TC.

Is there some documentation I'm missing about how to set `dbcluster` up and its the features?

My concern with using it is `ludicrousdb` has had some bugs in the past which they have been fixing, and they've been iterating on top of `hyperdb` for years. I don't have the same confidence about `dbcluster`. For example: https://github.com/stuttter/ludicrousdb/issues/55, https://github.com/stuttter/ludicrousdb/issues/53, https://github.com/stuttter/ludicrousdb/issues/72.

**Comment by cssjoe** [comment]
We'll be working on documentation and adding the item to our list.
