### ISSUE TITLE
Remove no-store header

### ISSUE THREAD

**Issue by mavas84** [BoldGrid/w3-total-cache#648]
Remove no-store header when using`("max-age=0, private, no-cache, no-store, must-revalidate")`  and only use no-cache instead:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
Reference topic: https://wordpress.org/support/topic/i-need-no-cache-header-without-no-store/

**Comment by MediaMaquina** [comment]
Not a contributor but, i would do it like this, cleaned up unneeded directives. Split in 2.
\inc\options\browsercache.php line 653
```
<option value="no_cache"<?php selected( $value, 'no_cache' ); ?>><?php esc_html_e( 'cache but always revalidate ("no-cache")', 'w3-total-cache' ); ?></option>
						<option value="no_store"<?php selected( $value, 'no_store' ); ?>><?php esc_html_e( 'never cache ("no-store")', 'w3-total-cache' ); ?></option>
```
BrowserCache_Environment.php line 573
```
			case 'no_cache':
				$headers_rules .= "        Header set Pragma \"no-cache\"\n";
				$headers_rules .= "        Header set Cache-Control \"no-cache\"\n";
				break;
			case 'no_store':
				$headers_rules .= "        Header set Pragma \"no-store\"\n";
				$headers_rules .= "        Header set Cache-Control \"no-store\"\n";
				break
```
There may be other places where it needs to be updated. Also I'm changing only html cache.
