### ISSUE TITLE
Maintain other meta_query settings in pre_get_posts

### ISSUE THREAD

**Issue by kylegilman** [BoldGrid/w3-total-cache#651]
My plugin [Videopack ](https://wordpress.org/plugins/video-embed-thumbnail-generator/) modifies the Media Library [meta_query using the pre_get_posts filter](https://github.com/kylegilman/video-embed-thumbnail-generator/blob/e6c604f10bc9dae86e47ab216a59624563b9a6e4/src/admin/videopack-admin.php#L3339) in order to avoid showing attachments created by the plugin. It looks like w3tc does something similar except it overwrites any other meta_query data in the function [w3tc_modify_query_obj ](https://github.com/BoldGrid/w3-total-cache/blob/d2e7c4437799aeb07763d75a768f63d1df303ca5/Root_Loader.php#L238) and disables the meta_query my plugin has added. Could you modify this function to maintain the modified meta_query? I found [this explanation](https://wordpress.stackexchange.com/questions/72099/can-i-exclude-a-post-by-meta-key-using-pre-get-posts-function/72126#72126) helpful.

**Comment by cssjoe** [comment]
@kylegilman
As a test, please replace the lines https://github.com/BoldGrid/w3-total-cache/blob/d2e7c4437799aeb07763d75a768f63d1df303ca5/Root_Loader.php#L238-L246 with the following code and let us know if it works for you.
```
		// Get the existing meta query array, add ours, and then save it.
		$meta_query   = (array) $query->get( 'meta_query' );
		$meta_query[] = array(
			'key'     => 'w3tc_imageservice_file',
			'compare' => 'NOT EXISTS',
		);

		$query->set( 'meta_query', $meta_query );
```

**Comment by kylegilman** [comment]
Yes! That works perfectly. Thanks for the quick fix.
