### ISSUE TITLE
Minify / Combine not working as expected

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/w3-total-cache#656]
Please see screenshots.
![image](https://user-images.githubusercontent.com/5925563/219528788-6fe09704-3600-4cd2-93ec-72bc2188bcf5.png)
![image](https://user-images.githubusercontent.com/5925563/219528818-2667a51b-f3e2-4c85-a6cc-cb0b4a322024.png)
![image](https://user-images.githubusercontent.com/5925563/219528844-991169f6-727c-4dc9-9114-e6ec669179f5.png)

**Comment by isrgrajan** [comment]
I suggest disabling the minification option until the W3T team has fixed it. Instead, you can utilize the Autoptimize plugin.
