### ISSUE TITLE
Query strings cached with disk Enhanced method hard coded.

### ISSUE THREAD

**Issue by mavas84** [BoldGrid/w3-total-cache#674]

**Comment by cssjoe** [comment]
I recommended adding a button next to the "Accepted query strings" textarea input box to add the list we have for known query string argument key names -- Clicking the button would add the default keys to the list, sort, and unique (to remove duplicates).  The user can then modify the list and click to save as usual.

**Comment by AleksandarPredic** [comment]
@mavas84 thanks for opening the ticket about this issue. Let me add more context to why this is needed, as I described it in the ticket on WP.org.

It is needed to have the option to edit the list of default accepted query strings/values to be ignored for the page cache.

The default ignored query string values are defined in this class: /w3-total-cache/PgCache_QsExempts.php, method get_qs_exempts. They can not be modified or filtered, at least I don't know how. I also try reaching the support.

I have a case on the website where I need to remove the UTM and other parameters from the list of ignored parameters when the page cache is created. Example: when the user land on the site from the Google ads I need to serve the non-cached version, while for the direct URL access, without query strings I need to serve the cached page version. Currently, when the user land on the URL from the Google ads, the plugin is serving the cached version of the page as all the params in the query string are in the ignore list array.

I know there is a setting for accepted query strings, but I don’t need a cached version with the query strings. I need to bypass the cache.

There are more details and discussions about this issue on the WP.org forum here https://wordpress.org/support/topic/filter-ist-of-default-accepted-qs-key-values-to-be-ignored-for-page-cache/

Please let me know if I can help more.

**Comment by jellewebsols** [comment]
+1 for a filterable list of accepted query strings. One of our clients is running some campaigns with UTM parameters, when a user lands on his site, they also need to see an uncached version of that page. 

Our workaround for now is to set **define('DONOTCACHEPAGE', true);** for UTM GET parameters in wp-config.php, but a filterable list inside the settings of W3TC would make this easier to manage.
