### ISSUE TITLE
FSD CDN option cannot be unchecked.

### ISSUE THREAD

**Issue by mavas84** [BoldGrid/w3-total-cache#675]
The checkbox is active and can be unchecked, but on save it remains checked.
Changing the dropdown to a different engine and updating it then unchecking the checkbox works, however, it should work without changing the provider option in the dropdown.
.

**Comment by jacobd91** [comment]
Update 2.3.3 makes many changes to the UI of the plugin that may resolve the unidentified cause of this issue. For the moment this ticket will remain open until that update goes live and pending any further reporting of this issue
