### ISSUE TITLE
W3TC should also support sitemap.txt to ease learning and debugging

### ISSUE THREAD

**Issue by porg** [BoldGrid/w3-total-cache#683]
For learning/debugging the **Cache Preload** cycle, working with a plain text `sitemap.txt` would be so much easier. Please support this in W3TC!

## Reasoning

This has official backing! Because the official [SiteMap specification](https://sitemaps.org/protocol.html) under [Other Formats](https://sitemaps.org/protocol.html#otherformats) lists **Text File** as a [valid option](https://sitemaps.org/protocol.html#otherformats:~:text=You%20can%20provide%20a%20simple%20text%20file%20that%20contains%20one%20URL%20per%20line):

> You can provide a simple text file that contains one URL per line.

## Minimal sitemaps (URL only) in TXT or XML format are essentially the same

- XML just more verbose
- Short ▶️ [video loop](https://www.dropbox.com/s/hf70gh5qo1hwe5f/Sitemap-with-URL-only-essentially-the-same-in-TXT-and-XML.mp4?raw=1) showing that a minimal sitemap is essentially the same in TXT and XML:

![Short video loop showing that a minimal sitemap is essentially the same in the TXT and XML formats](https://user-images.githubusercontent.com/737143/236845865-ba1c981d-d83f-4f6a-a2c1-fb6b2e9342cb.mp4)

Because in the [XML tag definitions](https://sitemaps.org/protocol.html#xmlTagDefinitions) it is clearly stated that per `<url>` tag the only mandatory tag is a `<loc>` tag. Which is essentially the same as a plain text sitemap with one URL per line.

In your plain text:

    FIND:              (.*)
    REPLACE:  <url><loc>$1</loc></url>

At file start insert:

    <?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

At file end insert:

    </urlset>

Change the file extension from TXT to XML.

Et Voila: You have a valid XML sitemap. Mine [validated](https://www.xml-sitemaps.com/validate-xml-sitemap.html) positive.

In the learning/debugging session which by itself is anyhow unnerving admins sure would be happy to spare themselves that extra conversion effort and just work with a simple one URL per line `sitemap.txt`

What do you say?

**Comment by cssjoe** [comment]
@porg We do have a prime cache feature that can cache a specified sitemap URL -- `wp-admin/admin.php?page=w3tc_pgcache`
We do not have plans to make a sitemap converter (TXT to XML).  WordPress redirects common sitemap URL requests to either `wp-sitemap.xml` or `?sitemap=index`; see https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/sitemaps/class-wp-sitemaps-index.php#L78-L96 -- We prefer to let WordPress handle sitemaps.  If you want to override it, there are sitemap plugins that may be useful.  If you place your sitemap file in your filesystem, then WordPress should not redirect to its dynamically generated `wp-sitemap.xml` file.

**Comment by porg** [comment]
Thanks for your answer.

Among the points you addressed, you also wrote: 
> We do not have plans to make a sitemap converter (TXT to XML)

As I pointed out plaintext *is* a valid sitemap format per the sitemap.org spec. So why not support it? That reason I'd like to know.
