### ISSUE TITLE
Save html cache files directly to S3

### ISSUE THREAD

**Issue by hj-collab** [BoldGrid/w3-total-cache#709]
Hi,

Many people run websites in a cluster. It will be great for them if W3tc saves the generated cache files directly to S3 bypassing the file system. There are some plugins for media library but none for cache. CDN will cache the S3 files after first request ensuring fast loading the after first request.

Best regards,

**Comment by cssjoe** [comment]
We recommend using full-site delivery, which will create page caching on CDN edges.
