### ISSUE TITLE
Existing offsite URLs modified after CDN

### ISSUE THREAD

**Issue by ajaxStardust** [BoldGrid/w3-total-cache#713]
Greetings. I think I may have done something wrong during setup. I'm not sure. 

I don't own a regular CDN subscription, but I see Google Drive as an option so I tried that. I realize it states PUSH only, but I thought I'd see what it did. 

I could be wrong, but I think this resulted in offsite links not working anymore. It seems they've been appended to the permalink for whatever is the post containing those links. 

E.g. https://wordpresscenter.net/web-browser-extension/
I noticed this when I clicked on a link to one of the browser extensions I have listed there. I didn't see anything in the faq addressing such an issue, so it leads me to think maybe something else caused this. I did not modify my permalink settings. 

Do you have a recommended way to revert this change (if i caused it during W3TC config)? I'm not certain it's associated w/ W3 Total Cache, but that's the only major change that happened before I noticed this. 

Thank you!
Your extension definitely improves the page load speed! Thank you!

**Comment by mavas84** [comment]
Hey @ajaxStardust 

Sorry for the late reply. Please note that we are using Github for specific and confirmed Bugs and not as a support channel.
I am not quite sure what the exact problem is so providing more details and possibly a screenshot would be great.

Please reach out to us directly via the plugin in Performance>Support or the [website contact form](https://www.w3-edge.com/contact/).

Thanks!

**Comment by ajaxStardust** [comment]
don't worry about it. that's a long time ago bro. done and done. very unpleasant situation. i've seen your correspondence in the forums. the user is at fault, and your software is free problematic issues. i don't have time for it.
best regards.
