### ISSUE TITLE
Deprecated: Creation of dynamic property W3TC\_CallUnderlying::$wpdb_mixin is deprecated

### ISSUE THREAD

**Issue by andre1808** [BoldGrid/w3-total-cache#733]
Hi there,

I've installed your plugin to our website.
When enabling Debug unfortunately it's throwing the following error:
Deprecated: Creation of dynamic property W3TC\_CallUnderlying::$wpdb_mixin is deprecated in /www/htdocs/w01307c2/tcw71/wp-content/plugins/w3-total-cache/DbCache_WpdbNew.php on line 352

I'm running PHP 8.2 on my wordpress installation.

Thanks for your help!
André

**Comment by cssjoe** [comment]
@andre1808 Thank you for reporting the issue when using PHP 8.2.  We have a fix staged for the next release.
