### ISSUE TITLE
ObjectCache_WpObjectCache does not support flush_group

### ISSUE THREAD

**Issue by c0ntax** [BoldGrid/w3-total-cache#738]
`flush_group` was introduced to `WP_Object_Cache` in WP 6.1.0 and I'm guessing should be added to ensure parity?

**Comment by harryjackson1221** [comment]
Thanks for reporting @c0ntax! Going to close this one, because we have this request in already based on the WP release: https://github.com/BoldGrid/w3-total-cache/issues/710
