### ISSUE TITLE
object cache - consider removing disk engines

### ISSUE THREAD

**Issue by maxicus** [BoldGrid/w3-total-cache#755]
In real world oc is used in code as ultrafast memory storage.
being pre-built it tends to have more data per object comparing to database sql response to generate this object, and combined with slower reaction...
espcially in modern hosting environments where disk is network-mounted...
using pure database (even slow database) becomes faster than using disk-based object cache.

So the only case when it can be useful is when there's no RAM for some very large object cache, but purge operations on disk cache are very costly comparing to RAM-based, what kills that usage case.

As a result:
- if someone understands what he is doing - he will rather allocate RAM space for cache than using disk
- if large object storage is needed - he will set up key-value persistent database like redis and its always designed to work with large object sets better than filesystem
- if not - will switch on what's seems most affordable - disk, and suffer performance degradation.

I suggest to remove disk options for OC engine.

**Comment by cssjoe** [comment]
I recommend keeping the disk option for the object cache but showing a warning/disclaimer if "disk" is selected.  We can also create an article and link to it, which can explain different storage options and the benefits and performance levels.

**Comment by jamieburchell** [comment]
Aren't frequently accessed data from disks cached in RAM by the OS?

**Comment by cssjoe** [comment]
@jamieburchell Yes, operating systems often cache frequently accessed data from disks in RAM.  W3TC is a more persistent version of caching.  The objects cached to disk most likely remain longer than they would by an OS's disk caching in RAM.
