### ISSUE TITLE
Cache expiration (auto purge)

### ISSUE THREAD

**Issue by mavas84** [BoldGrid/w3-total-cache#767]
In W3 Total Cache, The TTL of page cache files is set via the "Expires header lifetime" field in the "HTML" section on the Browser Cache Settings tab.
The Garbage collection interval is also involved in this and creates the _old files which should be deleted by the GC depending on the interval.
Suggestion: Create a dedicated option in the Page Cache settings for cache expiry, that can be configured to purge the cache every x hours or minutes. And GC interval should only delete the _old files that are created on the cache purge depending on the interval

**Comment by cssjoe** [comment]
Use `pgcache.lifetime` instead of `browsercache.html.lifetime` and ensure that garbage collection only removes the "_old" files in the `pgcache.file.gc` interval.
