### ISSUE TITLE
Mcrypt deprecated in Azure library

### ISSUE THREAD

**Issue by npr-gh** [BoldGrid/w3-total-cache#839]
Mcrypt (deprecated and removed in php7.2) in lib/azure/microsoftAzureStorage/Common/Internal/Utilities.php

Line 678-717 of this file; 

```
    public static function ctrCrypt($data, $key, $initializationVector) 
    {
        Validate::isString($data, 'data');
        Validate::isString($key, 'key');
        Validate::isString($initializationVector, 'initializationVector');
        
        Validate::isTrue(
            (strlen($key) == 16 || strlen($key) == 24 || strlen($key) == 32), 
            sprintf(Resources::INVALID_STRING_LENGTH, 'key', '16, 24, 32')
        );
        
        Validate::isTrue(
            (strlen($initializationVector) == 16), 
            sprintf(Resources::INVALID_STRING_LENGTH, 'initializationVector', '16')
        );

        $blockCount = ceil(strlen($data) / 16);
    
        $ctrData = '';
        for ($i = 0; $i < $blockCount; ++$i) {
            $ctrData .= $initializationVector;
    
            // increment Initialization Vector
            $j = 15;
            do {
                $digit                    = ord($initializationVector[$j]) + 1;
                $initializationVector[$j] = chr($digit & 0xFF);
                
                $j--;
            } while (($digit == 0x100) && ($j >= 0));
        }
        $encryptCtrData = mcrypt_encrypt(
            MCRYPT_RIJNDAEL_128, 
            $key, 
            $ctrData, 
            MCRYPT_MODE_ECB
        );
        
        return $data ^ $encryptCtrData;
    }

```
mcrypt is long deprecated and no longer a default part of PHP. This is the only part of the entire codebase that references it. It would seem introducing this dependency is undesirable. As-is: This is a trap: it won't work at all on modern PHP installations.

The complexity of cryptographic algorithms (or rather: overcomplication by adding too many options) and historic cruft makes it really difficult to update this to use say openssl instead. I have an inkling that this is roll-your-own-crypto, and the entire thing (untested) might be replace-able by a single call to 
```
return openssl_encrypt($data, "aes-128-ctr", $key, OPENSSL_RAW_DATA, $initializationVector);
``` 
That is, provided this is actually a proper 'CTR' encryption and not some strange microsofty-thing that's named the same but does something different. At first glance, https://github.com/openssl/openssl/blob/master/crypto/modes/ctr128.c#L40 looks the same at a glance... but there may be subtle bugs. What if it fails one in a billion times?

But before wasting a bunch of time, what about removing it entirely, as it's unused?

**Comment by cssjoe** [comment]
@npr-gh Thank you for your post.  We will be looking into providing updates to Azure support.
