### ISSUE TITLE
Consider removing outdated FAQ link from top nav

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/w3-total-cache#841]
There's a link to FAQs in the top nav:
![faq-link](https://github.com/BoldGrid/w3-total-cache/assets/20601160/73549420-9a28-4fe2-abf1-f8a24c9bb022)

It goes here - https://github.com/BoldGrid/w3-total-cache/wiki/FAQ - which hasn't been updated since 2018. Since this info is so outdated, I recommend removing the FAQ link.

**Comment by cssjoe** [comment]
@nicolepaschen Although the information may not be regularly updated, it does provide useful information, which is still relevant and helpful.
