### ISSUE TITLE
us-east-1 (default region) is not used in the Cloudfront hostname

### ISSUE THREAD

**Issue by bctrainers** [BoldGrid/w3-total-cache#845]
us-east-1. is missing from the $region field for CdnEngine_CloudFront.php

When _get_origin() function is using the `us-east-1` AWS datacenter, an error results in the CDN portal for "Test S3 Upload & Cloudfront Distribution". CdnEngine_CloudFront.php appears to not be populating the URL correctly when using this datacenter region. Per the code below, it's never being populated correctly due to the $region variable nullifying it.

```php
        /**
         * Returns origin
         */
        function _get_origin() {
                if ( $this->_config['bucket_location'] === 'us-east-1' ) {
                        $region = "";
                } else {
                        $region = $this->_config['bucket_location'] . '.';
                }
                return sprintf( '%s.s3.%samazonaws.com', $this->_config['bucket'], $region );
        }
```
https://github.com/BoldGrid/w3-total-cache/blob/bc461c2ad0d82cb00cc868bd786a010ff4657f94/CdnEngine_CloudFront.php#L151

When modifying line 151, changing a single line to the following:

```php
        /**
         * Returns origin
         */
        function _get_origin() {
                if ( $this->_config['bucket_location'] === 'us-east-1' ) {
                        $region = "us-east-1.";
                } else {
                        $region = $this->_config['bucket_location'] . '.';
                }
                return sprintf( '%s.s3.%samazonaws.com', $this->_config['bucket'], $region );
        }
```
The "Test S3 Upload & Cloudfront Distribution" will report "Test passed".

I am unsure if this would be a cosmetic bug or something far more reaching...

**Comment by cssjoe** [comment]
@bctrainers We are looking into adding another select option to include the default region in the hostname for S3 push operations.

**Comment by cssjoe** [comment]
@bctrainers The commit to branch fix-issue-845 adds another select option for the non-standard use of the full hostname with the default region.  Feel free to test it and let us know if it works.
