### ISSUE TITLE
Feature Request: add github repo link to the plugin support page

### ISSUE THREAD

**Issue by shoulders** [BoldGrid/w3-total-cache#851]
At the bottom of this page put a link to the GitHub repo with maybe a note saying for developers only.

`wp-admin/admin.php?page=w3tc_support`

![image](https://github.com/BoldGrid/w3-total-cache/assets/319997/b3e36e2b-91a1-4fae-9aea-27058ec04e20)

**Comment by cssjoe** [comment]
@shoulders The support forms are for paid support requests, submitting bug reports, and sales questions.  The GitHub issues are for developers and are mostly used for internal purposes.
