### ISSUE TITLE
Bug: Page Cache (Disk Enhanced) - Folders not being deleted after I move WordPress from a sub folder

### ISSUE THREAD

**Issue by shoulders** [BoldGrid/w3-total-cache#852]
## The background

- My client hade a live site in their root (`www.example.com`) so I developed the WordPress site in `www.example.com/wordpress/`.
- I installed  Total cache and enabled page cache (Disk Enhanced)
- Once I had completed the WP site I deleted the old site and moved the WP site into the root, updated sitelinks and URLs as normal and all is working.
- I played around with Total Cache settings to get a better experience etc.. but still I had `Page Cache (Disk Enhanced)` enabled
- Whilst in the root I have emptied `All caches` multiple times

### The issue
![image](https://github.com/BoldGrid/w3-total-cache/assets/319997/2e2b85fa-c19d-47be-a51a-f9df0cef0df4)

- When I navigate to `public_html/wp-content/cache/page_enhanced/www.example.com/` the **/wordpress/** folder is still present.
- If you go into **/wordpress/** you can see all of my page names indicating it is not a page called wordpress.
- Emptying `All page caches` does not get rid of this **/wordpress/** folder

### Requested solution

Improve the page cache purge logic to delete all unwanted folders and files, not just expired entries that match up with existing pages so situations like this when I move my site, all of the cached pages from the other location are deleted as well

**Comment by cssjoe** [comment]
@shoulders It is possible to have multiple WordPress installations under a domain (one or more subfolders), so the purge operation should only address cache items for the current WordPress installation.  If you migrate an installation, you should perform cache file cleanup manually (FTP/SSH/File Manager).

**Comment by shoulders** [comment]
I think the whole folder structure should be purged when you click `empty all caches`, folders + files

but I can use FTP for now. 😄
