### ISSUE TITLE
Feature: Add Enable/Disable button in the dashboard

### ISSUE THREAD

**Issue by shoulders** [BoldGrid/w3-total-cache#856]
### The background 

- I like to install Total Cache along with other plugins when I first setup the site so I can import all of the default settings.

### The issue

When Total cache is enable, the browser cache and sometimes other things can get in the way while I develop the content of the site and to prevent this I have to disable Total Cache via the plugins menu which is not ideal.

### Proposed solution

Can you add a `Enable/Disable` button in the dashboard to allow for easy development without the need to turn the plugin on or off.

![image](https://github.com/BoldGrid/w3-total-cache/assets/319997/e1e5ff98-2d8f-4d7f-a213-811cc8ebd2d3)

**Comment by cssjoe** [comment]
@shoulders Thank you for your new feature request.  Unfortunately, the feature would not be easy to implement and we prefer to focus on higher-priority issues.  We are closing this issue and can consider it at a later date if it becomes a popular request.  For now, please deactivate the plugin and reactivate it as needed.
