### ISSUE TITLE
Proposal: database optimization capabilities like delete post revision

### ISSUE THREAD

**Issue by nigrosimone** [BoldGrid/w3-total-cache#858]
WP Rocket has database optimization capabilities:
![image](https://github.com/BoldGrid/w3-total-cache/assets/310077/884499b5-0826-4fe8-9c26-16f6dfa87eba)
![image](https://github.com/BoldGrid/w3-total-cache/assets/310077/b32daab9-61dc-454d-af4c-27a590feee34)

Why [w3-total-cache](https://github.com/BoldGrid/w3-total-cache) don't implement this feature?

see https://github.com/wp-media/wp-rocket/blob/8694042889742c774a640e5eceebdd8e06c7ec69/inc/Engine/Admin/Database/OptimizationProcess.php

**Comment by cssjoe** [comment]
@nigrosimone Thank you for your suggestion.  We feel that such optimization/cleanup features are outside the scope of our plugin.  We may consider related features in the future.
