### ISSUE TITLE
Page cache clears each time w3_pgcache_cleanup runs if browsercache.html.lifetime > W3TC_CACHE_FILE_EXPIRE_MAX

### ISSUE THREAD

**Issue by jamieburchell** [BoldGrid/w3-total-cache#861]
I've been trying to troubleshoot why my enhanced page cache is getting cleared every time the `w3_pgcache_cleanup` cron job runs. I traced it to this line of code in the constructor of the `Cache_File_Cleaner_Generic` class:

```
if ( !$this->_expire || $this->_expire > W3TC_CACHE_FILE_EXPIRE_MAX ) {
    $this->_expire = 0;
}
```

The constant `W3TC_CACHE_FILE_EXPIRE_MAX` is `2592000` and my `browsercache.html.lifetime` configuration value is `31536000`.

There are a few issues here:

- Nobody knows this limit exists, and less that if you exceed it, your cache will expire every time. It makes more sense to set this value to `W3TC_CACHE_FILE_EXPIRE_MAX` if `$this->_expire > W3TC_CACHE_FILE_EXPIRE_MAX`
- It's not clear that the `browsercache.html.lifetime` config value has any relation to the purging of files from disk. One would reasonably assume based on the description of the field in the admin and related help that this setting is purely to control the header values that are sent.
- Why does the limit need to exist?

**Comment by cssjoe** [comment]
@jamieburchell We will look into adding more information on the settings page to inform users of the max value.  You can override the max value by adding a definition for `W3TC_CACHE_FILE_EXPIRE_MAX` in your `wp-config.php` file.

**Comment by jamieburchell** [comment]
Thanks @cssjoe. I did just that to resolve it.
Why is an upper limit necessary at all?

**Comment by DaanG47** [comment]
I also experience this problem. Page cache is set to a year, but when the cron "w3_pgcache_cleanup" runs, all cache is purged.
W3 Total Cache Version 2.7.1

**Comment by jamieburchell** [comment]
Thanks @cssjoe !

You mention a further bug where a field is hidden when the cache is Disk (Enhanced). How does the value of that previously hidden field relate to the browser cache expiry value?

**Comment by cssjoe** [comment]
@jamieburchell Another one of our devs worked on https://github.com/BoldGrid/w3-total-cache/pull/870 where the Page Cache lifetime setting was hidden but still used when using the Page Cache "Disk Enhanced" engine.  There is a relation between the page cache lifetime and what is used for the browser cache Expires headers.  We try to sync the lifetime so that browsers will get a new copy after the page cache expires.

**Comment by jamieburchell** [comment]
@cssjoe So does the newly visible field override the value set for the browser cache lifetime in respect of the disk cache expiry?

**Comment by cssjoe** [comment]
@jamieburchell I was mistaken.  The Browse Cache `ExpiresByType` headers for pages are controlled by `browsercache.html.expires` and `browsercache.html.lifetime`.

**Comment by jamieburchell** [comment]
@cssjoe Yes but `browsercache.html.lifetime` was also used as the expiry for the disk cache files. Is that no longer the case?

**Comment by cssjoe** [comment]
@jamieburchell That code was written before I was a part of the project.  It appears that `browsercache.html.lifetime` is used for manual cleanup for Page Cache when using Disk Enhanced.

**Comment by jamieburchell** [comment]
@cssjoe So one setting applies during cleanup but another controls expiry of the cache file? I'm confused 😊

**Comment by jamieburchell** [comment]
> @jamieburchell That code was written before I was a part of the project. It appears that `browsercache.html.lifetime` is used for manual cleanup for Page Cache when using Disk Enhanced.

@cssjoe Now that I see an input field for `pgcache.lifetime` in the settings I'm thinking [this line](https://github.com/BoldGrid/w3-total-cache/blob/180ba4f70d85fd674d0a5ec4ce78563e1e509510/PgCache_Plugin_Admin.php#L97) should reference that rather than `browsercache.html.lifetime` ?
