### ISSUE TITLE
When does w3-total-cache support pointing to pre-cache?

### ISSUE THREAD

**Issue by osr5** [BoldGrid/w3-total-cache#864]
When does w3-total-cache support pointing to pre-cache?

**Comment by cssjoe** [comment]
W3 Total Cache is capable of priming cache for pages.  Please review your settings.  The following links may help.
https://www.boldgrid.com/support/w3-total-cache/setup-guide-wizard/
https://www.boldgrid.com/support/w3-total-cache/preload-requests/
