### ISSUE TITLE
Object cache is disabled but object-cache.php is placed in wp-content

### ISSUE THREAD

**Issue by E1NSER** [BoldGrid/w3-total-cache#873]
We have experienced some strange behavior. We disabled the "**object cache**" in the plugin, but the file "**object-cache.php**" is placed in the wp-content directory. When the file is there, the WooCommerce pages that are not cached, like the checkout, are super slow. If we remove this file because we don't need it. Checkout of WooCommerce is about 7-10 times faster.

Every time we visit the settings of the plugin or the plugin section the file appears again which is super annoying because we have to watch every click in the backend to make sure the file doesn't come back which would drastically slow down some essential parts of the website.

**Comment by E1NSER** [comment]
any news?

**Comment by cssjoe** [comment]
We see that the file is removed after disabling the Object Cache engine.  If you still see the file in `wp-content`, then it may be placed by another plugin or there is some restriction on the server that prevents the file from being deleted by PHP.
