### ISSUE TITLE
Add MailChimp embed code for newsletter to footer 

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/w3-total-cache#874]
Please reach out to Elana Davis for the embed code / more information. She may just submit a pull request for the work. This is sort of a placeholder ticket for now.

**Comment by elanasparkle** [comment]
Updated pull request is here: 

https://github.com/BoldGrid/w3-total-cache/pull/875

![image](https://github.com/BoldGrid/w3-total-cache/assets/5271694/f7e51217-c079-4ca2-8e76-fbb0e13dc85c)
