### ISSUE TITLE
When will w3-total-cache support mouse pointer loading like wp-rocket? Not page caching.

### ISSUE THREAD

**Issue by osr5** [BoldGrid/w3-total-cache#876]
When will w3-total-cache support mouse pointer loading like wp-rocket? Not page caching.

**Comment by mavas84** [comment]
Hello @osr5 

Thank you for reaching out. I believe you are referring to the Delay scripts feature which already exists in the W3 Total Cache, Performance>General Settings>User Experience
Please make sure you [check out the documentation](https://www.boldgrid.com/support/w3-total-cache/delay-scripts-tool/) for this feature. 
Thanks!
