### ISSUE TITLE
Managed Identity support for Azure Blob Storage integratation

### ISSUE THREAD

**Issue by ZubaeyrMSFT** [BoldGrid/w3-total-cache#903]
Currently, access key for Azure Blob Storage account is stored in the database. Storing access tokens is generally not recommended. And furthermore, these tokens need to be rotated periodically. Azure's User Assigned Managed Identity automates the process of accessing the Azure resources without having to store or manage the access keys.

Are there any plans to provide Managed Identity option with Azure Blob Storage usage in W3TC plugin?

**Comment by cssjoe** [comment]
We are currently working on providing a solution for Microsoft Azure Managed Identities.
