### ISSUE TITLE
Fatal error: Call to undefined function W3TCL\Minify\fpassthru()

### ISSUE THREAD

**Issue by onwp** [BoldGrid/w3-total-cache#912]
Incident report:

Call to undefined function W3TCL\Minify\fpassthru() in /public_html/wp-content/plugins/w3-total-cache/lib/Minify/Minify/Cache/File.php:124

WordPress Version: 6.5.5
PHP Version: 8.2.19

**Comment by cssjoe** [comment]
@onwp [fpassthru](https://www.php.net/manual/en/function.fpassthru.php) is a PHP native function.  It may be possible that it is a disabled function in your PHP configuration.  You can check your `php.ini` file to see if `fpassthru` is listed in [disable_functions](https://www.php.net/manual/en/ini.core.php#ini.disable-functions).
Another thing you can try is adding a backslash before the function call to force it to use the global version of the function.  If you still see an "undefined function" error, then it is unavailable in your installation of PHP.  https://github.com/BoldGrid/w3-total-cache/blob/2.7.3/lib/Minify/Minify/Cache/File.php#L124 -- change to:
```
@\fpassthru($fp);
```

**Comment by onwp** [comment]
I'll check that. Thanks.
