### ISSUE TITLE
Add more "default" query strings keys to Page Cache

### ISSUE THREAD

**Issue by alexgarciab** [BoldGrid/w3-total-cache#924]
I suggest adding more "default" query string keys to Page Cache in regards to parameters used by the main Advertising Networks. These parameters are:

- ttclid > TikTok Ads Click ID
- wbraid > Google Ads Click ID (post iOS14)
- tblci > Taboola Ads Click ID
- dicbo > Outbrain Ads Click ID
- ScCid > Snapchat Ads Click ID
- click_id > Reddit Ads Click ID
- li_fat_id > Linkedin Ads Click ID
- twclid > Twitter Ads Click ID

These should be added in this file: **PgCache_QsExempts.php**

**Comment by alexgarciab** [comment]
@cssjoe any plans to add these keys?

**Comment by cssjoe** [comment]
@alexgarciab Thank you.  We'll include this request in our next release.
