### ISSUE TITLE
Publishing a new post forces WT3C to delete the cache of all posts in a multisite wordpress

### ISSUE THREAD

**Issue by mbouchard** [BoldGrid/w3-total-cache#929]
The following commit is the cause of this issue: https://github.com/BoldGrid/w3-total-cache/commit/8eee488313c611a822d0817e0c15de9d66a40b0f

It appears that changing the `delete_blog` action for `wp_uninitialize_site` and `wp_update_site` changed the initial desired behavior.

More specifically, the `wp_update_site` action happens to be triggered when a post is published.

```
wp_update_post -> wp_insert_post -> wp_transition_post_status -> _update_blog_date_on_post_publish -> wpmu_update_blogs_date -> 
update_blog_details -> wp_update_site -> on_change -> w3tc_flush_posts
```

Here is a purge log backtrace entry to illustrate this:

```
#0 wp-includes/class-wp-hook.php(324): W3TC\PgCache_Plugin--w3tc_flush_posts (null)
#1 wp-content/plugins/w3-total-cache/CacheFlush_Locally.php(167): do_action ("w3tc_flush_posts", null)
#2 wp-content/plugins/w3-total-cache/Util_AttachToActions.php(156): W3TC\CacheFlush--flush_posts ()
#3 wp-includes/class-wp-hook.php(326): W3TC\Util_AttachToActions--on_change ({"blog_id":"1","domain":"www.test.com","path":"/","site_id":"1","registered":"2020-12-0..)
#4 wp-includes/ms-site.php(197): do_action ("wp_update_site", {"blog_id":"1","domain":"www.test.com","path":"/","site_id":"1","registered":"2020-12-0.., {"blog_id":"1","domain":"www.test.com","path":"/","site_id":"1","registered":"2020-12-0..)
#5 wp-includes/ms-blogs.php(313): wp_update_site (1, {"domain":"www.test.com","path":"/","registered":"2020-12-02 21:22:51","last_updated":"..)
#6 wp-includes/ms-blogs.php(22): update_blog_details (1, {"last_updated":"2024-07-25 18:09:24"})
#7 wp-includes/ms-blogs.php(855): wpmu_update_blogs_date ()
#8 wp-includes/class-wp-hook.php(324): _update_blog_date_on_post_publish ("publish", "publish", {"ID":237078,"post_author":"1254","post_date":"2024-07-25 14:01:26","post_date_gmt":"2024-07-25 18..)
#9 wp-includes/post.php(5458): do_action ("transition_post_status", "publish", "publish", {"ID":237078,"post_author":"1254","post_date":"2024-07-25 14:01:26","post_date_gmt":"2024-07-25 18..)
#10 wp-includes/post.php(4718): wp_transition_post_status ("publish", "publish", {"ID":237078,"post_author":"1254","post_date":"2024-07-25 14:01:26","post_date_gmt":"2024-07-25 18..)
#11 wp-includes/post.php(4930): wp_insert_post ({"post_author":1254,"post_content":".!-- wp:paragraph --.\n.p..strong.Test.., false, true)
#12 wp-admin/includes/post.php(453): wp_update_post ({"ID":237078,"post_author":1254,"post_date":"2024-07-25 14:01:26","post_date_gmt":"2024-07-25 18:0..)
#13 wp-admin/post.php(227): edit_post ()
```
This behavior is problematic in a site with a very large amount of posts where several new posts are published during the day. The cache ends up being emptied far too frequently and the performance of the site suffers greatly.

**Comment by cssjoe** [comment]
The [delete_blog](https://developer.wordpress.org/reference/hooks/delete_blog/) hook became deprecated, so we are now using [wp_uninitialize_site](https://developer.wordpress.org/reference/hooks/wp_uninitialize_site/), which is fired when deleting a multisite blog site.  The hook still performs the same action -- flush posts.  We are working to target flushing to avoid clearing the entire cache.

**Comment by mbouchard** [comment]
I think the hook for `wp_update_site` should be something like this in order to call `onchange` only when deleting a blog:

```php
add_action( 'wp_update_site', function( $new_blog, $old_blog ) {
    if( !$old_blog->deleted && $new_blog->deleted ) {
        $o = new Util_AttachToActions();
        $o->on_change();
    }
}, 0, 2 );
```

**Comment by mbouchard** [comment]
@cssjoe I don't understand why this issue was closed since the problem I submitted is not fixed.

Replacing the delete_blog hook with wp_uninitialize_site and wp_update_site is not equivalent. I submitted a simple idea to fix the problem by modifying the declaration of the wp_update_site hook. This modification should bring back the behavior to the way it was before.

I hope you will consider reopening this issue since the current behavior can cause serious performance issues.

**Comment by cssjoe** [comment]
@mbouchard We'll look into it.  Thanks.

**Comment by cssjoe** [comment]
@mbouchard I created a [pull request](https://github.com/BoldGrid/w3-total-cache/pull/936) which addresses the reported issue and more.  Please test it and let us know if it works well for you.

**Comment by mbouchard** [comment]
@cssjoe I confirm that the problem is now resolved.
