### ISSUE TITLE
Settings not saved in the Cloudflare extension

### ISSUE THREAD

**Issue by mavas84** [BoldGrid/w3-total-cache#943]
In the W3TC Cloudflare extension - Performance>Extensions>Cloudflare - Settings, once the checkboxes for **Flush Cloudflare on Post Modifications** and **Exclude minified JS files from being processed by Rocket Loader** are checked, and save all settings, those settings are not saved and the checkboxes remain unchecked.

![image](https://github.com/user-attachments/assets/62d2c0da-eeac-48a6-ab41-d197987a1748)

In the Performance>General Settings, under the Exclude minified JS files from being processed by Rocket Loader section the **Flush Cloudflare on Post Modifications** checkbox can be checked and settings saved.

![image](https://github.com/user-attachments/assets/94e44fc1-ff33-4b02-a5be-f971bdbe5366)

**Comment by avonville** [comment]
Notes from the review:

- Remove the options from the extension settings page
- Add the options to the general settings page.
