### ISSUE TITLE
Allow user to add custom Cache Control params : s-max-age, stale-while-revalidate...etc

### ISSUE THREAD

**Issue by jouskaSockets** [BoldGrid/w3-total-cache#962]
Would be Great if i can set custom Cache Control policy and i can include my own values such as s-max-age or stale-while-revalidate, Because in cases where i need File to be cached for an hour on users browsers but for longer time on CDN s-max-age is required.

**Comment by cssjoe** [comment]
CDNs should observe `maxage` by default and use it as `s-maxage` in its absence.  You can set custom headers in your `.htaccess` file or other web server configuration file(s).
