### ISSUE TITLE
Remove or Adjust Unnecessary Notice for Inapplicable Settings

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/w3-total-cache#982]
The notice was alarming to me, I thought I had done something wrong. I don't have database cache enabled, the notice isn't applicable to me at this time because I cannot do anything to resolve the issue.

![image](https://github.com/user-attachments/assets/cb52afff-4359-46e0-929d-d51af931bc21)

**Comment by cssjoe** [comment]
The notice no longer appears when the engine is disabled.
